include $(APPDIR)/Make.defs

# 构建开关由 Kconfig 的 CONFIG_ASR_SDM_DRIVERS_ICM42688 控制
MODULE	=	$(CONFIG_ASR_SDM_DRIVERS_ICM42688)
CSRCS	=	icm42688.c

# 如需对外暴露本目录头文件给其它模块，取消注释：
# INCDIR	+=	$(APPDIR)/asr_sdm_drivers/icm42688

include $(APPDIR)/Application.mk


